version: '3.8'

services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project-lol-discord-bot
    env_file:
      - .env.production
    restart: unless-stopped
    networks:
      - discord-bot-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "bun", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # Uncomment if you need to expose ports for health checks or metrics
    # ports:
    #   - "3000:3000"

networks:
  discord-bot-network:
    driver: bridge