version: '3.8'

services:
  discord-bot:
    build:
      context: ../..              # monorepo root
      dockerfile: apps/discord/Dockerfile
    container_name: project-lol-discord-bot
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - discord-bot-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "bun", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  discord-bot-network:
    driver: bridge